### ISSUE TITLE
Свитчеры в настройках

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [pemakhov/react-native-internship#10]
Скорее всего где-то не совпало значение по умолчанию для свитчера и реального значения

https://user-images.githubusercontent.com/59687966/148832287-32b6ddbf-36b6-4ecf-bca2-0532d5eb9382.mov

**Comment by DmitriiMelnikOnix** [comment]
Они так странно переключаются только при первом нажатии

**Comment by pemakhov** [comment]
Исправил.
Добавил в экшнкриэйтерах, которые фетчат дефолтные значения из AsyncStorage, значения по-умолчанию на случай, если данные еще не хранились и AsyncStorage вернет null. Вроде как проблема была в этом.
