### ISSUE TITLE
Мелочь с username

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [pemakhov/react-native-internship#11]
Подчеркивает красным поле после небольших манипуляций. Если ты его стираешь сам, то лучше не показывать это как ошибку

https://user-images.githubusercontent.com/59687966/148832827-30b6f843-1fe5-4f7f-a0d0-61858edd8703.mov

**Comment by pemakhov** [comment]
Сделал.
Из валидации убрал isRequired.
Сделал чтобы кнопка сабмита была неактивна если не dirty
