### ISSUE TITLE
push в массивах

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [pemakhov/react-native-internship#12]
1. Я предпочитаю не использовать `push` чтобы обойтись без мутаций.

```
 acc.push({ title: item.sectionTitle, data: [item] });
 return acc
```
Можно заменить на что-то вроде
```
return [...acc, { title: item.sectionTitle, data: [item]}]
```

2. И сразу еще одно замечание

`getSectionedData` в `Home.js`

```
flatData.reduce((acc, item) => {
      const section = acc.find(
      ....
```
В этом случае можно заменить на `map`

3. И теперь когда я разобрался в коде
Перепиши `getSectionedData` без использования мутаций

В `getSectionedData` есть вот такая строка
```
section.data.push(item);
```
она добавляет элемент в `section.data`, но `section` это ссылка на элемент в `flatData`, который в свою очередь являться `data` из `state.spaceObjects`. То есть вот такой строкой ты изменяешь данные в редаксе, но так как это происходит через мутацию, реакт этих изменений не отслеживает. Может вылезти боком, и никто не сможет понять почему

**Comment by DmitriiMelnikOnix** [comment]
На 2й пункт можешь не обращать внимания. На `map` не получится переделать

**Comment by pemakhov** [comment]
done
