### ISSUE TITLE
Eslint

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [pemakhov/react-native-internship#8]
Не стоит отключать правила eslint если это не оправданно конкретной ситуацией
Такие строки кода как
```
 {errors.name && <Text style={styles.error}>{errors.name}</Text>}
 { traveler && <SignOutButton handleSignOut={() => dispatch(deleteTraveler())} />}
```
очень бросаются в глаза, потому что пробелы используются по разному

**Comment by pemakhov** [comment]
done
