### ISSUE TITLE
Еще немного о структуре

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [pemakhov/react-native-internship#9]
Я бы предложил немного переделать структуру файлов в скринах
```
- screens
-- SpaceObject
--- SpaceObject.js
--- styles.js
--- components
---- Divider.js (только файл без папок)
---- InfoRow.js (только файл без папок)
```

Стили для `Divider.js` и `InfoRow.js` использовать из файла `SpaceObject/styles.js`
Так структура будет чуть более плоской

**Comment by pemakhov** [comment]
Переделал в соответствии с предложенным вариантом
